services:
  - type: web
    name: django-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn tu_proyecto.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tu_proyecto.settings
      - key: SECRET_KEY
        value: "tu_clave_secreta"
    databases:
      - name: db